spring.application.name=datapi

# URL dinámica: usa localhost en local, mysql-db dentro de docker
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:integrajobdb}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Usuario y password: por defecto usa jrgazmuri/jrgazmuri si no se pasa nada
spring.datasource.username=${DB_USER:jrgazmuri}
spring.datasource.password=${DB_PASSWORD:jrgazmuri}

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082

# BNE API Token
bne.api.token-url=https://test.api.bne.cl/token
bne.api.client-id=e9b75m_XYbA5n0Dz33M_rbChsRMa
bne.api.client-secret=bbctfOeNTfCyfhNa_xOl5kafYvMa
