bne:
  api:
    base-url: https://test.api.bne.cl
    token-url: https://test.api.bne.cl/oauth/token
    client-id: ${BNE_CLIENT_ID}
    client-secret: ${BNE_CLIENT_SECRET}
  import:
    limit: 100
    total: 1000
  page-limit: 100
  total-deseado: 1000