spring.application.name=datapi
spring.datasource.url=jdbc:mysql://localhost:3306/integrajobdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=jrgazmuri
spring.datasource.password=jrgazmuri
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
